apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: webhook-service-account
  namespace: your-namespace  # Replace with your webhook's namespace
roleRef:
  kind: ClusterRole
  name: webhook-cluster-role
  apiGroup: rbac.authorization.k8s.io
